#port => default : 8080 => 
#spring => 데이터베이스 (datasource)
# LOCAL_DB_URL => jdbc어떠고 로컬아이피 환경변수 새로 만듦

spring:
  datasource:
    url: ${LOCAL_DB_URL} 
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver 
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
# mybatis 
mybatis:
  type-aliases-package: com.sist.web.vo
  mapper-locations: mybatis/mapper/*.xml
